# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-root-password
            - name: MYSQL_DATABASE
              value: mysql-deployment
            - name: MYSQL_USER
              value: my-username
            - name: MYSQL_PASSWORD
              value: my-password
          volumeMounts:                 
            - name: mysql-pvc
              mountPath: /var/lib/mysql
      volumes:                        
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
