# result-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-deployment
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-server
  template:
    metadata:
      labels:
        app: result-server
    spec:
      containers:
        - name: result-server
          image: brunnerlan/result-server-app
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE_HOST
              value: "mysql-service"  # Name des MySQL Service
            - name: MYSQL_USER
              value: "username"  # Benutzername für die MySQL-Datenbank
            - name: MYSQL_PASSWORD
              value: "password"  # Passwort für die MySQL-Datenbank
            - name: MYSQL_DATABASE
              value: "database"  # Name der MySQL-Datenbank
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
