# result-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-deployment
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-server
  template:
    metadata:
      labels:
        app: result-server
    spec:
      containers:
        - name: result-server
          image: brunnerlan/result-server-app
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE_HOST
              value: mysql-deployment.my-apps.svc.cluster.local
            - name: MYSQL_USER
              value: my-username
            - name: MYSQL_PASSWORD
              value: my-password
            - name: MYSQL_DATABASE
              value: my-database-name
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15